name: PlayerVaults
main: muqsit\playervaults\PlayerVaults
api: 5.3.0
version: 3.5.3
commands:
  playervault:
    permission: playervaults.command
    description: "Open your vaults"
    aliases: ["pv", "ec"]
permissions:
  playervaults.command:
    default: true
  playervaults.vault.1:
    default: true
  playervaults.vault.2:
    default: true
  playervaults.vault.3:
    default: true
  playervaults.others.edit:
    default: op
  playervaults.others.view:
    default: op